version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

  skip-dirs:
    - vendor

linters:
  enable:
    - lll
    - misspell
    - gosec
    # - revive
    - goconst
  settings:
    lll:
      line-length: 120
    goimports:
      local-prefixes: github.com/Norgate-AV/netlinx-language-server
    revive:
      # Max number of issues to report (default: 50)
      # max-issues-per-linter: 50
      # Max number of same issues (default: 3)
      # max-same-issues: 3
      # Disable specific rules
      # ignore-generated-header: true
      # Configure specific rules
      # formatter: stylish
      severity: warning
      rules:
        # For your comment issues:
        - name: exported
          severity: warning  # or error
          disabled: true    # set to true to disable this rule
          # arguments:
          #   - "disableStutteringCheck"

        # For naming conventions:
        - name: var-naming
          severity: warning
          disabled: true

        # For package comments:
        - name: package-comments
          severity: warning
          disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

formatters:
  enable:
    - gofmt
    - goimports
