version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

  skip-dirs:
    - vendor

linters:
  enable:
    - lll
    - misspell
    - gosec
    # - revive
    - goconst

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/Norgate-AV/netlinx-language-server

formatters:
  enable:
    - gofmt
    - goimports
