version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

  skip-dirs:
    - vendor

linters:
  enable:
    # - errcheck
    # - gofmt
    # - goimports
    # - gosimple
    - govet
    - ineffassign
    # - staticcheck
    # - typecheck
    # - unused
    # - lll

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/Norgate-AV/netlinx-language-server
